[package]
name = "the-way"
version = "0.11.1"
edition = "2018"
authors = ["Ninjani"]
description = "A code snippets manager for your terminal"
repository = "https://github.com/out-of-cheese-error/the-way"
readme = "README.md"
license = "MIT"
keywords = ["cli", "code", "snippets"]
categories = ["command-line-utilities"]
exclude = [
    "tests/",
    "ci/",
    ".travis.yml",
]

[dependencies]
# Argument parsing
structopt = "0.3.20"

# Configuration management
confy = "0.4.0"
directories-next = "1.0.2"

# Error management
eyre = "0.6.1"
color-eyre = { version = "0.5.6", default-features = false }
thiserror = "1.0.21"

# Database related
sled = "0.34.4"
bincode = "1.3.1"

# Serializing
serde = "1.0.117"
serde_json = "1.0.59"
serde_derive = "1.0.117"
serde_yaml = "0.8.13"

# Parsing and manipulating dates
chrono = { version = "0.4.19", features = ["serde"] }
chrono-english = "0.1.4"

# Taking user input and showing progress
dialoguer = "0.7.1"
indicatif = "0.15.0"

# Fuzzy search
skim = "0.9.1"

# Terminal syntax highlighting
syntect = { version = "4.4.0", default-features = false, features = ["default-fancy"] }
hex = "0.4.2"

# Sync to Gist/GitLab
ureq = { version = "1.5.1", features = ["json"] }

# pattern filter and filling shell script variables
regex = "1.4.1"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
tempfile = "3.1.0"
rexpect = "0.4.0"

[target.'cfg(target_os = "macos")'.dev-dependencies]
clipboard = "0.5.0"
