[package]
name = "the-way"
version = "0.4.0"
edition = "2018"
authors = ["Ninjani"]
description = "A code snippets manager for your terminal"
repository = "https://github.com/out-of-cheese-error/the-way"
readme = "README.md"
license = "MIT"
keywords = ["cli", "code", "snippets"]
categories = ["command-line-utilities"]
exclude = [
    "tests/",
    "ci/",
    ".travis.yml"
]

[dependencies]
# Argument parsing
structopt = "0.3.14"

# Configuration management
confy = "0.4.0"
directories-next = "1.0.0"

# Error management
eyre = "0.5"
color-eyre = { version = "0.4.1", default-features = false }
thiserror = "1.0.15"

# Database related
sled = "0.31.0"
bincode = "1.2.1"

# Serializing
serde = "1.0.106"
serde_json = "1.0.51"
serde_derive = "1.0.106"
serde_yaml = "0.8.11"

# Parsing and manipulating dates
chrono = { version = "0.4.11", features = ["serde"] }
chrono-english = "0.1.4"

# Taking user input and showing progress
dialoguer = "0.6.2"
indicatif = "0.15.0"

# Fuzzy search
skim = "0.8.1"

# Terminal syntax highlighting
syntect = { version = "4.2", default-features = false, features = ["default-fancy"]}
hex = "0.4.2"

# Sync to Gist/GitLab
reqwest = {version="0.10.4", features=["json", "blocking"]}

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.4"
tempfile = "3.1.0"
rexpect = "0.3"

[target.'cfg(target_os = "macos")'.dev-dependencies]
clipboard = "0.5.0"