[package]
name = "the-way"
version = "0.14.4"
edition = "2018"
authors = ["Ninjani"]
description = "A code snippets manager for your terminal"
repository = "https://github.com/out-of-cheese-error/the-way"
readme = "README.md"
license = "MIT"
keywords = ["cli", "code", "snippets"]
categories = ["command-line-utilities"]
exclude = [
    "tests/",
    "ci/",
    ".travis.yml",
]

[dependencies]
# Argument parsing
structopt = "0.3.25"

# Configuration management
confy = "0.4.0"
directories-next = "1.0.2"

# Error management
eyre = "0.6.5"
color-eyre = { version = "0.5.11", default-features = false }
thiserror = "1.0.30"

# Database related
sled = "0.34.7"
bincode = "1.3.3"

# Serializing
serde = "1.0.133"
serde_json = "1.0.74"
serde_derive = "1.0.133"
serde_yaml = "0.8.23"

# Parsing and manipulating dates
chrono = { version = "0.4.19", features = ["serde"] }
chrono-english = "0.1.7"

# Taking user input and showing progress
dialoguer = "0.9.0"
indicatif = "0.16.2"

# Fuzzy search
skim = "0.9.4"

# Terminal syntax highlighting
syntect = { version = "4.6.0", default-features = false, features = ["default-fancy"] }
hex = "0.4.3"

# Sync to Gist/GitLab
ureq = { version = "2.4.0", features = ["json"] }

# pattern filter and filling shell script variables
regex = "1.5.4"

[dev-dependencies]
assert_cmd = "2.0.2"
predicates = "2.1.0"
tempfile = "3.2.0"
rexpect = "0.4.0"

[target.'cfg(target_os = "macos")'.dev-dependencies]
clipboard = "0.5.0"

[package.metadata.deb]
extended-description-file = "README.md"
