[package]
name = "the-way"
version = "0.2.0"
edition = "2018"
authors = ["Ninjani"]
description = "A code snippets manager for your terminal"
repository = "https://github.com/out-of-cheese-error/the-way"
readme = "README.md"
#license = "MIT OR Apache-2.0" # TODO: add license
keywords = ["cli", "snippets"]
categories = ["cli-tools"]

[dependencies]
# Argument parsing
structopt = "0.3.14"
clap = {version="2.33", features = ["yaml"]}
confy = "0.4.0"

# Error management
anyhow = "1.0.28"
thiserror = "1.0.15"

# Path and file related
directories = "2.0.2"

# Database related
sled = "0.31.0"
bincode = "1.2.1"

# Serializing
serde = "1.0.106"
serde_json = "1.0.51"
serde_derive = "1.0.106"
serde_yaml = "0.8.11"

# Parsing and manipulating dates
chrono = { version = "0.4.11", features = ["serde"] }
chrono-english = "0.1.4"

# Taking user input
dialoguer = "0.5.0"

# Fuzzy search
skim = "0.8.1"

# Copy to clipboard
clipboard = "0.5.0"

# Terminal syntax highlighting
syntect = "4.1.1"
hex = "0.4.2"