[package]
name = "the-way"
version = "0.2.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
# Argument parsing
clap = {git = "https://github.com/clap-rs/clap/", version = "3.0.0-beta.1", features = ["yaml"]}

# Error management
anyhow = "1.0.28"
thiserror = "1.0.15"

# Path and file related
dirs = "2.0.2"
path_abs = "0.5.0"

# Database related
sled = "0.31.0"
bincode = "1.2.1"
# Serializing
serde = "1.0.106"
serde_json = "1.0.51"
serde_derive = "1.0.106"
serde_yaml = "0.8.11"

# Parsing and manipulating dates
chrono = { version = "0.4.11", features = ["serde"] }
chrono-english = "0.1.4"

# Taking user input
dialoguer = "0.5.0"

# Graphs in the terminal
tui = "0.6.2"
termion = "1.5.5"
textwrap = { version = "0.11.0", features = ["term_size"] }

# Fuzzy search
skim = "0.8.1"

# Copy to clipboard
clipboard = "0.5.0"

# Terminal syntax highlighting
syntect = "4.1.1"
console = "0.10.0"